-- Server-only access with forced RLS defense in depth.
revoke all on schema support_private from public, anon, authenticated, service_role;
grant usage on schema support_private to support_web_runtime;
grant select on support_private.schema_contract to support_web_runtime;
revoke all on schema support_identity_accounts from public, anon, authenticated, service_role;
grant usage on schema support_identity_accounts to support_web_runtime;
revoke all on all tables in schema support_identity_accounts from public, anon, authenticated, service_role;
grant select, insert, update, delete on all tables in schema support_identity_accounts to support_web_runtime;
alter default privileges in schema support_identity_accounts revoke all on tables from public, anon, authenticated, service_role;
alter default privileges in schema support_identity_accounts grant select, insert, update, delete on tables to support_web_runtime;
revoke all on schema support_identity_account_emails from public, anon, authenticated, service_role;
grant usage on schema support_identity_account_emails to support_web_runtime;
revoke all on all tables in schema support_identity_account_emails from public, anon, authenticated, service_role;
grant select, insert, update, delete on all tables in schema support_identity_account_emails to support_web_runtime;
alter default privileges in schema support_identity_account_emails revoke all on tables from public, anon, authenticated, service_role;
alter default privileges in schema support_identity_account_emails grant select, insert, update, delete on tables to support_web_runtime;
revoke all on schema support_identity_authentication from public, anon, authenticated, service_role;
grant usage on schema support_identity_authentication to support_web_runtime;
revoke all on all tables in schema support_identity_authentication from public, anon, authenticated, service_role;
grant select, insert, update, delete on all tables in schema support_identity_authentication to support_web_runtime;
alter default privileges in schema support_identity_authentication revoke all on tables from public, anon, authenticated, service_role;
alter default privileges in schema support_identity_authentication grant select, insert, update, delete on tables to support_web_runtime;
revoke all on schema support_identity_profiles from public, anon, authenticated, service_role;
grant usage on schema support_identity_profiles to support_web_runtime;
revoke all on all tables in schema support_identity_profiles from public, anon, authenticated, service_role;
grant select, insert, update, delete on all tables in schema support_identity_profiles to support_web_runtime;
alter default privileges in schema support_identity_profiles revoke all on tables from public, anon, authenticated, service_role;
alter default privileges in schema support_identity_profiles grant select, insert, update, delete on tables to support_web_runtime;
revoke all on schema support_identity_social_graph from public, anon, authenticated, service_role;
grant usage on schema support_identity_social_graph to support_web_runtime;
revoke all on all tables in schema support_identity_social_graph from public, anon, authenticated, service_role;
grant select, insert, update, delete on all tables in schema support_identity_social_graph to support_web_runtime;
alter default privileges in schema support_identity_social_graph revoke all on tables from public, anon, authenticated, service_role;
alter default privileges in schema support_identity_social_graph grant select, insert, update, delete on tables to support_web_runtime;
revoke all on schema support_enterprises_enterprises from public, anon, authenticated, service_role;
grant usage on schema support_enterprises_enterprises to support_web_runtime;
revoke all on all tables in schema support_enterprises_enterprises from public, anon, authenticated, service_role;
grant select, insert, update, delete on all tables in schema support_enterprises_enterprises to support_web_runtime;
alter default privileges in schema support_enterprises_enterprises revoke all on tables from public, anon, authenticated, service_role;
alter default privileges in schema support_enterprises_enterprises grant select, insert, update, delete on tables to support_web_runtime;
revoke all on schema support_enterprises_enterprise_memberships from public, anon, authenticated, service_role;
grant usage on schema support_enterprises_enterprise_memberships to support_web_runtime;
revoke all on all tables in schema support_enterprises_enterprise_memberships from public, anon, authenticated, service_role;
grant select, insert, update, delete on all tables in schema support_enterprises_enterprise_memberships to support_web_runtime;
alter default privileges in schema support_enterprises_enterprise_memberships revoke all on tables from public, anon, authenticated, service_role;
alter default privileges in schema support_enterprises_enterprise_memberships grant select, insert, update, delete on tables to support_web_runtime;
revoke all on schema support_enterprises_enterprise_roles from public, anon, authenticated, service_role;
grant usage on schema support_enterprises_enterprise_roles to support_web_runtime;
revoke all on all tables in schema support_enterprises_enterprise_roles from public, anon, authenticated, service_role;
grant select, insert, update, delete on all tables in schema support_enterprises_enterprise_roles to support_web_runtime;
alter default privileges in schema support_enterprises_enterprise_roles revoke all on tables from public, anon, authenticated, service_role;
alter default privileges in schema support_enterprises_enterprise_roles grant select, insert, update, delete on tables to support_web_runtime;
revoke all on schema support_enterprises_enterprise_teams from public, anon, authenticated, service_role;
grant usage on schema support_enterprises_enterprise_teams to support_web_runtime;
revoke all on all tables in schema support_enterprises_enterprise_teams from public, anon, authenticated, service_role;
grant select, insert, update, delete on all tables in schema support_enterprises_enterprise_teams to support_web_runtime;
alter default privileges in schema support_enterprises_enterprise_teams revoke all on tables from public, anon, authenticated, service_role;
alter default privileges in schema support_enterprises_enterprise_teams grant select, insert, update, delete on tables to support_web_runtime;
revoke all on schema support_organizations_organizations from public, anon, authenticated, service_role;
grant usage on schema support_organizations_organizations to support_web_runtime;
revoke all on all tables in schema support_organizations_organizations from public, anon, authenticated, service_role;
grant select, insert, update, delete on all tables in schema support_organizations_organizations to support_web_runtime;
alter default privileges in schema support_organizations_organizations revoke all on tables from public, anon, authenticated, service_role;
alter default privileges in schema support_organizations_organizations grant select, insert, update, delete on tables to support_web_runtime;
revoke all on schema support_organizations_organization_memberships from public, anon, authenticated, service_role;
grant usage on schema support_organizations_organization_memberships to support_web_runtime;
revoke all on all tables in schema support_organizations_organization_memberships from public, anon, authenticated, service_role;
grant select, insert, update, delete on all tables in schema support_organizations_organization_memberships to support_web_runtime;
alter default privileges in schema support_organizations_organization_memberships revoke all on tables from public, anon, authenticated, service_role;
alter default privileges in schema support_organizations_organization_memberships grant select, insert, update, delete on tables to support_web_runtime;
revoke all on schema support_organizations_organization_teams from public, anon, authenticated, service_role;
grant usage on schema support_organizations_organization_teams to support_web_runtime;
revoke all on all tables in schema support_organizations_organization_teams from public, anon, authenticated, service_role;
grant select, insert, update, delete on all tables in schema support_organizations_organization_teams to support_web_runtime;
alter default privileges in schema support_organizations_organization_teams revoke all on tables from public, anon, authenticated, service_role;
alter default privileges in schema support_organizations_organization_teams grant select, insert, update, delete on tables to support_web_runtime;
revoke all on schema support_organizations_organization_roles from public, anon, authenticated, service_role;
grant usage on schema support_organizations_organization_roles to support_web_runtime;
revoke all on all tables in schema support_organizations_organization_roles from public, anon, authenticated, service_role;
grant select, insert, update, delete on all tables in schema support_organizations_organization_roles to support_web_runtime;
alter default privileges in schema support_organizations_organization_roles revoke all on tables from public, anon, authenticated, service_role;
alter default privileges in schema support_organizations_organization_roles grant select, insert, update, delete on tables to support_web_runtime;
revoke all on schema support_organizations_organization_policies from public, anon, authenticated, service_role;
grant usage on schema support_organizations_organization_policies to support_web_runtime;
revoke all on all tables in schema support_organizations_organization_policies from public, anon, authenticated, service_role;
grant select, insert, update, delete on all tables in schema support_organizations_organization_policies to support_web_runtime;
alter default privileges in schema support_organizations_organization_policies revoke all on tables from public, anon, authenticated, service_role;
alter default privileges in schema support_organizations_organization_policies grant select, insert, update, delete on tables to support_web_runtime;
revoke all on schema support_organizations_custom_properties from public, anon, authenticated, service_role;
grant usage on schema support_organizations_custom_properties to support_web_runtime;
revoke all on all tables in schema support_organizations_custom_properties from public, anon, authenticated, service_role;
grant select, insert, update, delete on all tables in schema support_organizations_custom_properties to support_web_runtime;
alter default privileges in schema support_organizations_custom_properties revoke all on tables from public, anon, authenticated, service_role;
alter default privileges in schema support_organizations_custom_properties grant select, insert, update, delete on tables to support_web_runtime;
revoke all on schema support_repositories_repositories from public, anon, authenticated, service_role;
grant usage on schema support_repositories_repositories to support_web_runtime;
revoke all on all tables in schema support_repositories_repositories from public, anon, authenticated, service_role;
grant select, insert, update, delete on all tables in schema support_repositories_repositories to support_web_runtime;
alter default privileges in schema support_repositories_repositories revoke all on tables from public, anon, authenticated, service_role;
alter default privileges in schema support_repositories_repositories grant select, insert, update, delete on tables to support_web_runtime;
revoke all on schema support_repositories_repository_access from public, anon, authenticated, service_role;
grant usage on schema support_repositories_repository_access to support_web_runtime;
revoke all on all tables in schema support_repositories_repository_access from public, anon, authenticated, service_role;
grant select, insert, update, delete on all tables in schema support_repositories_repository_access to support_web_runtime;
alter default privileges in schema support_repositories_repository_access revoke all on tables from public, anon, authenticated, service_role;
alter default privileges in schema support_repositories_repository_access grant select, insert, update, delete on tables to support_web_runtime;
revoke all on schema support_collaboration_conversations from public, anon, authenticated, service_role;
grant usage on schema support_collaboration_conversations to support_web_runtime;
revoke all on all tables in schema support_collaboration_conversations from public, anon, authenticated, service_role;
grant select, insert, update, delete on all tables in schema support_collaboration_conversations to support_web_runtime;
alter default privileges in schema support_collaboration_conversations revoke all on tables from public, anon, authenticated, service_role;
alter default privileges in schema support_collaboration_conversations grant select, insert, update, delete on tables to support_web_runtime;
revoke all on schema support_collaboration_discussions from public, anon, authenticated, service_role;
grant usage on schema support_collaboration_discussions to support_web_runtime;
revoke all on all tables in schema support_collaboration_discussions from public, anon, authenticated, service_role;
grant select, insert, update, delete on all tables in schema support_collaboration_discussions to support_web_runtime;
alter default privileges in schema support_collaboration_discussions revoke all on tables from public, anon, authenticated, service_role;
alter default privileges in schema support_collaboration_discussions grant select, insert, update, delete on tables to support_web_runtime;
revoke all on schema support_collaboration_issues from public, anon, authenticated, service_role;
grant usage on schema support_collaboration_issues to support_web_runtime;
revoke all on all tables in schema support_collaboration_issues from public, anon, authenticated, service_role;
grant select, insert, update, delete on all tables in schema support_collaboration_issues to support_web_runtime;
alter default privileges in schema support_collaboration_issues revoke all on tables from public, anon, authenticated, service_role;
alter default privileges in schema support_collaboration_issues grant select, insert, update, delete on tables to support_web_runtime;
revoke all on schema support_collaboration_moderation from public, anon, authenticated, service_role;
grant usage on schema support_collaboration_moderation to support_web_runtime;
revoke all on all tables in schema support_collaboration_moderation from public, anon, authenticated, service_role;
grant select, insert, update, delete on all tables in schema support_collaboration_moderation to support_web_runtime;
alter default privileges in schema support_collaboration_moderation revoke all on tables from public, anon, authenticated, service_role;
alter default privileges in schema support_collaboration_moderation grant select, insert, update, delete on tables to support_web_runtime;
revoke all on schema support_collaboration_projects from public, anon, authenticated, service_role;
grant usage on schema support_collaboration_projects to support_web_runtime;
revoke all on all tables in schema support_collaboration_projects from public, anon, authenticated, service_role;
grant select, insert, update, delete on all tables in schema support_collaboration_projects to support_web_runtime;
alter default privileges in schema support_collaboration_projects revoke all on tables from public, anon, authenticated, service_role;
alter default privileges in schema support_collaboration_projects grant select, insert, update, delete on tables to support_web_runtime;
revoke all on schema support_engagement_notifications from public, anon, authenticated, service_role;
grant usage on schema support_engagement_notifications to support_web_runtime;
revoke all on all tables in schema support_engagement_notifications from public, anon, authenticated, service_role;
grant select, insert, update, delete on all tables in schema support_engagement_notifications to support_web_runtime;
alter default privileges in schema support_engagement_notifications revoke all on tables from public, anon, authenticated, service_role;
alter default privileges in schema support_engagement_notifications grant select, insert, update, delete on tables to support_web_runtime;
revoke all on schema support_engagement_stars from public, anon, authenticated, service_role;
grant usage on schema support_engagement_stars to support_web_runtime;
revoke all on all tables in schema support_engagement_stars from public, anon, authenticated, service_role;
grant select, insert, update, delete on all tables in schema support_engagement_stars to support_web_runtime;
alter default privileges in schema support_engagement_stars revoke all on tables from public, anon, authenticated, service_role;
alter default privileges in schema support_engagement_stars grant select, insert, update, delete on tables to support_web_runtime;
revoke all on schema support_engagement_subscriptions from public, anon, authenticated, service_role;
grant usage on schema support_engagement_subscriptions to support_web_runtime;
revoke all on all tables in schema support_engagement_subscriptions from public, anon, authenticated, service_role;
grant select, insert, update, delete on all tables in schema support_engagement_subscriptions to support_web_runtime;
alter default privileges in schema support_engagement_subscriptions revoke all on tables from public, anon, authenticated, service_role;
alter default privileges in schema support_engagement_subscriptions grant select, insert, update, delete on tables to support_web_runtime;
revoke all on schema support_platform_audit_storage from public, anon, authenticated, service_role;
grant usage on schema support_platform_audit_storage to support_web_runtime;
revoke all on all tables in schema support_platform_audit_storage from public, anon, authenticated, service_role;
grant select, insert, update, delete on all tables in schema support_platform_audit_storage to support_web_runtime;
alter default privileges in schema support_platform_audit_storage revoke all on tables from public, anon, authenticated, service_role;
alter default privileges in schema support_platform_audit_storage grant select, insert, update, delete on tables to support_web_runtime;
revoke all on schema support_platform_event_publication from public, anon, authenticated, service_role;
grant usage on schema support_platform_event_publication to support_web_runtime;
revoke all on all tables in schema support_platform_event_publication from public, anon, authenticated, service_role;
grant select, insert, update, delete on all tables in schema support_platform_event_publication to support_web_runtime;
alter default privileges in schema support_platform_event_publication revoke all on tables from public, anon, authenticated, service_role;
alter default privileges in schema support_platform_event_publication grant select, insert, update, delete on tables to support_web_runtime;
revoke all on schema support_platform_notification_channels from public, anon, authenticated, service_role;
grant usage on schema support_platform_notification_channels to support_web_runtime;
revoke all on all tables in schema support_platform_notification_channels from public, anon, authenticated, service_role;
grant select, insert, update, delete on all tables in schema support_platform_notification_channels to support_web_runtime;
alter default privileges in schema support_platform_notification_channels revoke all on tables from public, anon, authenticated, service_role;
alter default privileges in schema support_platform_notification_channels grant select, insert, update, delete on tables to support_web_runtime;
revoke all on schema support_platform_scheduled_commands from public, anon, authenticated, service_role;
grant usage on schema support_platform_scheduled_commands to support_web_runtime;
revoke all on all tables in schema support_platform_scheduled_commands from public, anon, authenticated, service_role;
grant select, insert, update, delete on all tables in schema support_platform_scheduled_commands to support_web_runtime;
alter default privileges in schema support_platform_scheduled_commands revoke all on tables from public, anon, authenticated, service_role;
alter default privileges in schema support_platform_scheduled_commands grant select, insert, update, delete on tables to support_web_runtime;
revoke all on schema support_platform_media_storage from public, anon, authenticated, service_role;
grant usage on schema support_platform_media_storage to support_web_runtime;
revoke all on all tables in schema support_platform_media_storage from public, anon, authenticated, service_role;
grant select, insert, update, delete on all tables in schema support_platform_media_storage to support_web_runtime;
alter default privileges in schema support_platform_media_storage revoke all on tables from public, anon, authenticated, service_role;
alter default privileges in schema support_platform_media_storage grant select, insert, update, delete on tables to support_web_runtime;
revoke all on schema support_platform_search_index from public, anon, authenticated, service_role;
grant usage on schema support_platform_search_index to support_web_runtime;
revoke all on all tables in schema support_platform_search_index from public, anon, authenticated, service_role;
grant select, insert, update, delete on all tables in schema support_platform_search_index to support_web_runtime;
alter default privileges in schema support_platform_search_index revoke all on tables from public, anon, authenticated, service_role;
alter default privileges in schema support_platform_search_index grant select, insert, update, delete on tables to support_web_runtime;
revoke all on schema support_projections_dashboard from public, anon, authenticated, service_role;
grant usage on schema support_projections_dashboard to support_web_runtime;
revoke all on all tables in schema support_projections_dashboard from public, anon, authenticated, service_role;
grant select, insert, update, delete on all tables in schema support_projections_dashboard to support_web_runtime;
alter default privileges in schema support_projections_dashboard revoke all on tables from public, anon, authenticated, service_role;
alter default privileges in schema support_projections_dashboard grant select, insert, update, delete on tables to support_web_runtime;
revoke all on schema support_projections_activity_feed from public, anon, authenticated, service_role;
grant usage on schema support_projections_activity_feed to support_web_runtime;
revoke all on all tables in schema support_projections_activity_feed from public, anon, authenticated, service_role;
grant select, insert, update, delete on all tables in schema support_projections_activity_feed to support_web_runtime;
alter default privileges in schema support_projections_activity_feed revoke all on tables from public, anon, authenticated, service_role;
alter default privileges in schema support_projections_activity_feed grant select, insert, update, delete on tables to support_web_runtime;
revoke all on schema support_projections_discovery from public, anon, authenticated, service_role;
grant usage on schema support_projections_discovery to support_web_runtime;
revoke all on all tables in schema support_projections_discovery from public, anon, authenticated, service_role;
grant select, insert, update, delete on all tables in schema support_projections_discovery to support_web_runtime;
alter default privileges in schema support_projections_discovery revoke all on tables from public, anon, authenticated, service_role;
alter default privileges in schema support_projections_discovery grant select, insert, update, delete on tables to support_web_runtime;
revoke all on schema support_identity_account_registration from public, anon, authenticated, service_role;
grant usage on schema support_identity_account_registration to support_web_runtime;
revoke all on all tables in schema support_identity_account_registration from public, anon, authenticated, service_role;
grant select, insert, update, delete on all tables in schema support_identity_account_registration to support_web_runtime;
alter default privileges in schema support_identity_account_registration revoke all on tables from public, anon, authenticated, service_role;
alter default privileges in schema support_identity_account_registration grant select, insert, update, delete on tables to support_web_runtime;
revoke all on schema support_projections_search from public, anon, authenticated, service_role;
grant usage on schema support_projections_search to support_web_runtime;
revoke all on all tables in schema support_projections_search from public, anon, authenticated, service_role;
grant select, insert, update, delete on all tables in schema support_projections_search to support_web_runtime;
alter default privileges in schema support_projections_search revoke all on tables from public, anon, authenticated, service_role;
alter default privileges in schema support_projections_search grant select, insert, update, delete on tables to support_web_runtime;

do $$
declare
  relation record;
  policy_name text;
begin
  for relation in
    select schemaname, tablename
    from pg_tables
    where schemaname like 'support\_%' escape '\'
      and schemaname <> 'support_private'
  loop
    execute format('alter table %I.%I enable row level security', relation.schemaname, relation.tablename);
    execute format('alter table %I.%I force row level security', relation.schemaname, relation.tablename);
    policy_name := 'support_web_runtime_only';
    execute format('drop policy if exists %I on %I.%I', policy_name, relation.schemaname, relation.tablename);
    execute format(
      'create policy %I on %I.%I for all to support_web_runtime using (current_user = %L) with check (current_user = %L)',
      policy_name, relation.schemaname, relation.tablename, 'support_web_runtime', 'support_web_runtime'
    );
  end loop;
end
$$;

revoke all on function support_private.provision_supabase_user() from public, anon, authenticated, service_role;
revoke all on function support_private.sync_supabase_user_email() from public, anon, authenticated, service_role;
revoke all on function support_private.protect_last_organization_owner() from public, anon, authenticated, service_role;
